general:
  version: 1

pools:
  world: world_pools
  bedrock_level: 60
  floor_level: 62
  roof_min_height: 16
  roof_max_height: 64
  doorway_min_height: 2
  doorway_max_height: 4
  doorway_max_width_half: 3
  walkway_max_width_half: 5
  wall_probability: 0.75
  window_probability: 0.3
  island_probability: 0.75
  pool_probability: 0.75
  double_door_probability: 0.5
  food_probability: 0.01
  floor_blocks:
    - blue_concrete
    - light_blue_concrete
  wall_blacks:
    - polished_diorite
    - diorite
  ceiling_blacks:
    - polished_diorite
    - diorite
  light_blocks:
    - sea_lantern

dark_pools:
  world: world_dark_pools
  bedrock_level: 60
  floor_level: 62
  roof_min_height: 4
  roof_max_height: 10
  doorway_min_height: 2
  doorway_max_height: 4
  doorway_max_width_half: 3
  walkway_max_width_half: 5
  wall_probability: 0.75
  window_probability: 0.3
  island_probability: 0.75
  pool_probability: 0.75
  double_door_probability: 0.5
  food_probability: 0.01
  floor_blocks:
    - blue_concrete
    - light_blue_concrete
  wall_blacks:
    - polished_diorite
    - diorite
    - quartz_block
  ceiling_blacks:
    - polished_diorite
    - diorite
    - quartz_block
  light_blocks:
    - sea_lantern
  exit:
    min_distance: 640
    max_distance: 3200
    max_probability: 0.1
    command_blocks: true
    exit_level: -32

ocean:
  world: world_ocean
  sky_height: 32
  sand_level: 6
  bedrock_level: 1
